const antivirusSignatures = {
    '360 Total Security': ['360safe.dll'],
    'AhnLab V3': ['v3svc.dll'],
    'AOL Active Virus Shield': ['aolav.dll'],
    'ArcaBit': ['arcabitengine.dll'],
    'AVG': ['avgui.dll'],
    'Avast': ['avast.dll', 'aswEngineA.dll'],
    'Avira': ['avamsi.dll', 'avamsicli.dll', 'avcuf32.dll'],
    'Baidu Antivirus': ['bdhsvc.dll'],
    'Bitdefender': ['bdcore.dll', 'avc3.dll', 'atcuf64.dll', 'antimalware_provider64.dll'],
    'BullGuard': ['bullguard.dll', 'bgadriver.dll'],
    'ClamAV': ['libclamav.dll'],
    'Comodo': ['com_antivirus.dll', 'cavwp.dll'],
    'Dr.Web': ['dwengine.dll', 'drwebsp.dll'],
    'Emsisoft': ['a2cmd.dll'],
    'ESET': ['egui.dll', 'eks.dll'],
    'F-Secure': ['fsaus.dll', 'fsdfw.dll'],
    'Fortinet': ['fnetwizard.dll', 'fortinet_krn.dll'],
    'G Data': ['gdata_avi.dll', 'gdavflt.dll'],
    'K7 AntiVirus': ['k7sentry.dll', 'k7avgent.dll'],
    'Kaspersky': ['kavprot.dll', 'klif.dll'],
    'Malwarebytes': ['mbamswissarmy.dll'],
    'McAfee': ['mcafee.dll', 'mfehidk.dll'],
    'Norton': ['npsystem.dll', 'symcorpui.dll'],
    'Nscore': ['nscore64.dll'],
    'Panda': ['panda_url_filtering.dll', 'pavbootstartdriver.dll'],
    'Quick Heal': ['qhsafemain.dll', 'qhwtp.dll'],
    'Rising': ['ravmon.dll', 'rfapi.dll'],
    'Sophos': ['sophos_detoured.dll', 'savapi.dll', 'sav.dll'],
    'Symantec': ['symnav.dll', 'symcheck.dll'],
    'TotalDefense': ['sbamsvc.dll', 'tdrtac.dll'],
    'Trend Micro': ['tmntsrv.dll', 'tmwlutil.dll', 'vsapi32.dll'],
    'VirusBuster': ['vba32core.dll', 'vbadeint.dll'],
    'Webroot': ['wrsvc.dll', 'wrsa.dll'],
    //EXCEPTION: 'Windows Defender': ['msmpeng.exe', 'msmpsvc.dll'], //NOTE: Windows Defender is typically the recommended antivirus for heavily-modded Skyrim, so no warning is needed unless it shows up in the top half of the crash log (handled elsewhere)
    'ZoneAlarm': ['zavcore.dll', 'zlclient.dll']
};