// ./js/nolvusSignatures.js
window.nolvusSignatures = {
    'Nolvus': [
        'Nolvus Ascension Trees Addon.esp',
        'Seasons of Nolvus.esp',
        'Seasons of Nolvus - Solitude.esp',
        'Seasons of Nolvus - Riften.esp',
        'Seasons of Nolvus - Markarth.esp',
        'Seasons of Nolvus - Oakwood Patch.esp',
        'Nolvus Weapon Keywords.esp',
        'Nolvus Ascension Seasonal Tree Mashup.esp',
        'Nolvus Ascension Seasonal Grass Mashup.esp',
        'Nolvus Ascension Seasonal Plant Mashup.esp',
        'Nolvus Ascension Core Patch.esp',
        'Nolvus Ascension Container Patch.esp',
        'Nolvus Ascension Music Patch.esp',
        'Nolvus Ascension Sounds Patch.esp',
        'Nolvus Ascension DLC Patch.esp',
        'Nolvus Ascension Visual Base Patch.esp',
        'Nolvus Ascension Mountains Patch.esp',
        'Nolvus Acsension Flora Patch.esp',
        'Nolvus Ascension Weathers Patch.esp',
        'Nolvus Ascension NPC Patch.esp',
        'Nolvus Ascension Cities Patch.esp',
        'Nolvus Ascension Towns Patch.esp',
        'Nolvus Ascension Land Patch.esp',
        'Nolvus Ascension Player Home Patch.esp',
        'Nolvus Ascension Interiors Patch.esp',
        'Nolvus Ascension Armors Patch.esp',
        'Nolvus Ascension Clothes Patch.esp',
        'Nolvus Ascension Weapons Patch.esp',
        'Nolvus Ascension Creatures Patch.esp',
        'Nolvus Ascension Model Patch.esp',
        'Nolvus Ascension Perks Patch.esp',
        'Nolvus Ascension Survival Patch.esp',
        'Nolvus Ascension Crafting Patch.esp',
        'Nolvus Ascension Combat Patch.esp',
        'Nolvus Ascension Economy Patch.esp',
        'Nolvus Ascension AI Patch.esp',
        'Nolvus Ascension Misc Gameplay Patch.esp',
        'Nolvus Ascension Races Patch.esp',
        'Nolvus Ascension Immersion Patch.esp',
        'Nolvus Ascension Lighting Patch.esp',
        'Nolvus Meshes Patch.esp',
        'Nolvus Ascension Late Loader Patch.esp',
        'WDAL NOLVUS Dark Faces Patch.esp'
    ]
};